apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flowertune-cache-pvc
  namespace: flower-supernode-a
spec:
  accessModes:
    - ReadWriteMany  # CFS 支持多节点同时读写
  resources:
    requests:
      storage: 50Gi
  storageClassName: cfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flowertune-output-pvc
  namespace: flower-supernode-a
spec:
  accessModes:
    - ReadWriteMany  # CFS 支持多节点同时读写
  resources:
    requests:
      storage: 50Gi
  storageClassName: cfs
