apiVersion: v1
kind: Service
metadata:
  name: superlink-server-svc
  namespace: flower-superlink
spec:
  selector:
    app: superlink
  ports:  # like a dynamic IP routing table/mapping that routes traffic to the designated ports
  - protocol: TCP
    port: 9091
    targetPort: 9091
  type: ClusterIP
